### ISSUE TITLE
Port collision

### ISSUE THREAD

**Issue by MuschPusch** [MuschPusch/generator-jaMann#4]
jaMann gives you the same port every time :/

**Comment by stmh** [comment]
Not anymore. Now jamann queries via fabalicious every existing project and read its port-setting and compute from that a new unique port. (will only work with latest fabalicious-version, you'll get a warning otherwise)

Unfortunately you may still get port-collisions when multiple people use the same project.

The async nature of nodes makes the code a really mess. This needs some serious refactoring.
